title: Mineral Physics Group

logo: /assets/img/MPG.jpg

description: A special interest group of the <a href="https://www.minersoc.org/">Mineralogical Society of the UK and Ireland</a>. <br/>
                <br/>
                <a href="https://minphys.github.io/pre-release/RiP_2025/RiP_2025.html">ðŸ’Ž RiP 2025 meeting </a> <br/>
   
show_downloads: false

google_analytics: true

theme: jekyll-theme-minimal
